# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:3000', 'https://localhost:3000', 'https://devfuyang.fr'] # Ajoutez le port que votre app React utilise
        allow_methods: ['GET', 'POST', 'OPTIONS']
        allow_headers: ['Content-Type']
        expose_headers: []
        max_age: 3600
    paths:
        '^/message/': # Ajustez cette route si nécessaire
            allow_origin: ['http://localhost:3000', 'https://localhost:3000', 'https://devfuyang.fr']
