version: '3.8'
services:
  webservice:
    container_name: 'portfolio'
    build: './build/php/'
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    depends_on:
      - mysql-srv
  mysql-srv:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolio
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80 
    environment:
      - PMA_ARBITRARY=1
