version: 1
services:
  - type: web
    name: my-symfony-app
    env: node
    plan: starter
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php
      mv composer.phar /usr/local/bin/composer
      composer install
      yarn --frozen-lockfile install
      npm run build
    startCommand: "symfony server:start --no-tls"
    autoDeploy: true
